### ISSUE TITLE
--no-check-certificate is insecure

### ISSUE THREAD

**Issue by chrisfosterelli** [zouzias/docker-boost#1]
Why is this flag provided? This means that anyone who uses this image might not have a verified safe copy of boost.

**Comment by zouzias** [comment]
Hi Chris, I fixed it on #2 using Boost's releases from bintray. I also updated most docker images from Docker hub, see https://hub.docker.com/r/zouzias/boost/tags/

**Comment by chrisfosterelli** [comment]
Thank you!
