### ISSUE TITLE
change `ENV DEBIAN_FRONTEND noninteractive` to `ARG `

### ISSUE THREAD

**Issue by rl-enjoyer** [zouzias/docker-boost#4]
having `DEBIAN_FRONTEND` as ENV means it will persist down to containers that are built ontop this one. Additionally if you try and run this container interactively using say `docker run -it ... /bin/sh` you wont see anything. 

Switch it to an arg so that it only is used when the container is built and not when run. 

https://github.com/moby/moby/issues/4032

**Comment by rl-enjoyer** [comment]
Also https://docs.docker.com/engine/faq/#why-is-debian_frontendnoninteractive-discouraged-in-dockerfiles

**Comment by zouzias** [comment]
Thanks for reporting @NolanC33 . I pushed the images with tags 1.75.0 and 1.76.0 using ARGS, so non-interactive should be only used in the docker build process only now.

**Comment by rl-enjoyer** [comment]
Awesome! Thank you!
