### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by fzoric8** [zouzias/docker-boost#8]
Hi, 

I've tried to include your way to build specific boost version inside dockerfile, and I've followed all instructions and provided correct arguments, however I get following output of command like this: 
```
wget --max-redirect 3 https://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION_}.tar.gz
```
Args are set accordingly, but output of the command is following: 
```
--2021-06-01 13:51:09--  https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz
Resolving dl.bintray.com (dl.bintray.com)... 3.127.93.119, 18.196.33.98
Connecting to dl.bintray.com (dl.bintray.com)|3.127.93.119|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-06-01 13:51:09 ERROR 403: Forbidden.
```

Whichever version i use i get such error. 

Maybe i should sign up to `dl.bintray.com`?

**Comment by zouzias** [comment]
Thanks for reporting, it is actually related to https://www.boost.org/users/news/boost_has_moved_downloads_to_jfr.html

Should be fixed now.
